default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: localhost
  username: postgres
  password: postgres
  database: api_development

test:
  <<: *default
  host: localhost
  username: postgres
  password: postgres
  database: api_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
