source 'https://rubygems.org'
ruby '2.5.0'

# Ruby on Rails
gem 'rails', '~> 5.1.0'

# ActiveRecord
gem 'pg'

# Orchestration
gem 'puma'
gem 'foreman'
gem 'figaro'

# API
gem 'pragma-rails', '~> 2.0'

group :development do
  # Factories
  gem 'factory_bot_rails'
  gem 'faker'

  # Preloading
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'spring-watcher-listen'
end
